function Chat(props) {
  try {
    return (
      <>
        <h2>Chat</h2>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat reprehenderit expedita architecto labore dicta accusantium ut? Cum voluptatibus placeat, nemo minima ratione autem soluta neque quidem sapiente quod ab repellat aliquid excepturi magnam officia, illum incidunt, nostrum nisi minus enim possimus sequi. Ipsam earum voluptas repellat obcaecati itaque corrupti amet dolor
          consequuntur dolorum tempore. Nostrum esse dolor quasi blanditiis totam eligendi cumque tempora inventore quibusdam nisi accusamus fugit nemo adipisci, ut consectetur aspernatur aut. Quod architecto nostrum tempora dolores sunt doloribus officiis eos et, dolorum, officia excepturi pariatur voluptate assumenda ad repudiandae deleniti nihil? Nulla assumenda cupiditate nesciunt dolorum
          nobis, itaque error doloremque, quidem quam mollitia alias dicta sequi hic? Accusamus cumque praesentium adipisci quas et minima voluptate labore quae? Sunt nihil doloremque accusamus quaerat explicabo pariatur vel mollitia recusandae voluptatem neque modi, magnam ullam perspiciatis numquam inventore? Ipsa, excepturi atque reiciendis aperiam numquam quas quibusdam animi, dicta non eos
          asperiores soluta quisquam nostrum laborum reprehenderit incidunt aliquid vel rerum doloribus unde quasi a iusto consequuntur. Reiciendis, tenetur voluptas. Eaque porro saepe dolorum obcaecati repellat, impedit accusantium aperiam harum, distinctio odit consectetur eum eligendi corrupti, quasi voluptatem consequuntur sequi reprehenderit sit tenetur? Odit, voluptatem molestiae?
          Consectetur, architecto saepe? Omnis, quae.
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis ratione dignissimos debitis assumenda nostrum molestiae expedita in quam dolorem, sapiente numquam fugiat exercitationem soluta doloremque maxime cupiditate tempore perferendis odit? Ad fuga officia maxime quidem ullam, doloremque autem nemo aut voluptate deleniti facilis amet voluptates, error eius sint dolorum possimus
          animi tenetur? Hic perferendis tempora exercitationem, sunt facilis voluptatem tempore molestias provident eveniet ex consequatur, itaque saepe impedit praesentium. Doloremque reprehenderit quaerat error minus magni dolore corporis cum dolor suscipit molestias modi quas facilis, cupiditate doloribus repudiandae accusamus quam magnam aliquid assumenda quos blanditiis quo? Minima a natus
          sunt delectus amet eum iure culpa consectetur iste non saepe error ut possimus, labore illo impedit numquam. Corporis consectetur inventore nisi esse optio at molestiae sed sit repellendus odio reiciendis commodi ut dolorum quos, perspiciatis hic error! Reiciendis alias nihil quisquam corporis odio similique, commodi est dolorem qui ratione maiores inventore ullam tenetur, dolorum
          dignissimos sed voluptatibus. Nobis commodi fugit molestias voluptas! Corrupti ipsam commodi magnam voluptatibus quisquam veniam dolor maiores repudiandae assumenda quos voluptas illo doloribus, libero non expedita saepe perferendis modi sapiente ipsa amet? Magnam nisi doloribus porro! Officiis temporibus totam necessitatibus quis cumque doloremque qui quo molestiae architecto eum?
          Voluptas earum, illo exercitationem ipsum nihil architecto rerum, odit consequatur labore iusto blanditiis, maxime tempore. Quas magnam tenetur consequuntur iste perspiciatis suscipit sed doloribus quos praesentium, soluta velit vitae nihil sint ex voluptas! Officiis atque ut sint iste laboriosam impedit nisi rem modi dolores repellendus sit debitis minima totam ad natus quas, suscipit
          magnam maxime eum quam et dolorem nemo. Corrupti eaque corporis sequi perferendis, quo, tempora, dolores cum assumenda temporibus molestias quaerat est nobis voluptatum odio fugiat accusamus quibusdam id quod eius illum culpa? Amet facere dolorem ipsum vel magnam error voluptate ea neque perspiciatis corrupti? Labore, alias illum?
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium doloremque nobis eveniet exercitationem quos esse rerum! Facere, eius voluptas quam aliquid autem neque blanditiis enim nobis, modi minima accusantium possimus nesciunt rerum ratione rem sapiente ducimus! Esse soluta at dicta nam incidunt voluptate illo accusantium asperiores, ad ex provident vero impedit exercitationem
          possimus voluptas odio illum blanditiis repellat numquam id alias sequi! Corrupti atque ipsa amet omnis dolores, maxime, quae quis vero eos commodi, quos sunt vel ea velit tempora nihil! Aut cumque voluptates aperiam alias accusamus voluptate libero labore nesciunt minus, dolore, inventore odio quam, dolores excepturi rerum nam dolorum. Debitis ipsa non cumque, quaerat odio commodi
          doloribus laudantium quasi iure! Ullam, cum vero dolorum nisi neque, illo voluptatibus ex tempora aut quibusdam accusamus beatae explicabo delectus eaque rerum reiciendis doloremque laborum totam cupiditate est iste animi. Accusamus porro beatae dignissimos minus reiciendis cum voluptatibus veritatis illum ratione, debitis id, suscipit obcaecati quo aliquam quae, distinctio ab? Incidunt
          reprehenderit architecto nulla possimus natus voluptatem laborum doloremque molestias magnam recusandae! Quo quaerat quisquam nemo vero velit sapiente necessitatibus sit repellendus. Dignissimos eveniet minima omnis provident obcaecati enim ducimus, ab fugit similique error excepturi fuga optio placeat alias dolore quibusdam iure maiores corporis officia necessitatibus reiciendis. Porro
          quam expedita voluptatibus eos architecto quae quasi dolores ullam perspiciatis, ea iusto ipsam recusandae itaque corrupti ad nostrum placeat explicabo neque. Iure aperiam nam velit ducimus, consequatur repellat libero qui deserunt atque voluptatibus eius mollitia fuga eaque assumenda laborum culpa fugit perferendis corrupti. Dolor expedita numquam perspiciatis quia possimus ducimus
          ullam nostrum beatae itaque autem, nihil blanditiis vel unde tempora, cupiditate corrupti eaque voluptate quos ipsam quasi eos nobis. Adipisci, suscipit culpa sed aliquam nobis sapiente, repellendus odit deserunt hic earum laborum optio ex quasi voluptatibus, veniam natus non rem. Molestias inventore aspernatur debitis officia reiciendis veritatis corrupti animi nulla, ea magnam deserunt
          rem quaerat culpa asperiores facere mollitia voluptates velit quod molestiae odio esse temporibus id. Officia, excepturi harum nobis cumque itaque non dignissimos vero atque, ducimus necessitatibus optio. Molestiae, tempora? Officiis sapiente, repellendus, praesentium obcaecati ipsa ipsum repellat aliquid cum doloremque magni reprehenderit voluptas. Earum, soluta! Sequi eius minima
          soluta commodi consequatur, incidunt ullam numquam! Tempore, vero sint. Inventore vel temporibus incidunt iure illum laudantium dolorum voluptates. Obcaecati consequuntur ducimus quo rerum, dolor voluptatem quis quaerat numquam vel facere magni qui suscipit distinctio sint autem, eveniet, officiis dolorem! Harum sint laudantium corporis labore consequuntur pariatur ullam aut libero
          eligendi ducimus! Eos impedit molestiae vero mollitia quasi? Quisquam reiciendis, expedita, commodi eius, ipsa iusto ea ut voluptates porro sapiente officiis? At ea corporis consectetur. Perferendis veritatis iusto ratione cum, impedit natus voluptatum adipisci, quas amet nobis qui blanditiis tempora quidem dolorum exercitationem quasi. Recusandae, velit ipsam saepe reprehenderit, ipsum
          vitae iusto libero minima, fuga vel omnis eveniet. Necessitatibus voluptas quia ullam dolorem laudantium! Eveniet ut esse consequuntur, unde architecto necessitatibus rem assumenda iure eum cum vero rerum ducimus beatae illo tenetur maiores molestias ex quaerat voluptates. Debitis eius eligendi ipsum, quis exercitationem blanditiis.
        </p>
      </>
    );
  } catch (err) {
    console.log(err);
  }
}

export default Chat;
